version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "${PORT}:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ./app:/app
    networks:
      - code-network

networks:
  code-network:
    driver: bridge