version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "${PORT}:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    build: .
    volumes:
      - ./app:/app
    networks:
      - code-network
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=librairie
      - MYSQL_USER=webdev
      - MYSQL_PASSWORD=webdev
    ports:
      - "3306:3306"
    restart: always
    networks:
      - code-network

networks:
  code-network:
    driver: bridge